{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.fullname" . }}
  namespace: {{ template "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
{{- end -}}
{{- end }}

{{- if .Values.privateRegistry }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.fullname" . }}-privateregistry
  namespace: {{ template "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.privateRegistry.dockerconfigjson }}
{{- end }}
